### ISSUE TITLE
Uploading UDM2 asset to GEE - no metadata?

### ISSUE THREAD

**Issue by jkelly17** [samapriya/Planet-GEE-Pipeline-CLI#14]
Hey Sam,

I want to upload the Usable Data Mask .tif file associated with each PlanetScope Orthotile but I'm receiving an error that says "no metadata exists for image "xxxx" it will not be ingested". Now I was able to successfully upload the PSO files after updating to version 0.4.5, but I am confused on how I can upload the UDM2 assets if ppipe doesn't recognize the xml file associated with it. The UDM2 asset is essential for masking clouds, shadows, and other features, as I'm sure you know. 

Thanks,
Josh

**Comment by samapriya** [comment]
Hey @jkelly17 ,
UDM2 is an interesting case, so UDM2 does not have any metadata except the names. The way in which I approached this was

- I generated the metadata from the PSScene4Band analytic XML. 
- I renamed all the UDM2 files to match the PSScene4Band files. I did this by opening the metadata file and replacing the _UDM2 by nothing. 
- I uploaded the udm2 images which now have the same name as the 4band images them to a different image collection in Earth Engine. 

The other solution would be to use another tool called [geeup](https://github.com/samapriya/geeup) that I built that does not require a mf or manifest flag to upload, that way you won't have to change the filenames. In either case, I did not create a manifest for UDM2 because it is not truly an asset type with metadata attached. I hope that helps

**Comment by jkelly17** [comment]
Hey Sam,

If I opt for using the geeup method, the upload tool requires a metadata
folder argument. Why is this required if UDM2 is an asset without metadata?
What should I put in that folder?

Thanks,
Josh

**Comment by samapriya** [comment]
Hi @jkelly17 
So I end up putting in two things that are important to me 
1) The name of the image or udm2 
2) The system:start time which would be useful for sorting and filtering

Those are the two bare minima fields I would add to the image. The metadata from Planet and the metadata for Earth Engine are two different things here. Earth Engine requires metadata to organize images in the collection. Hope that helps
